GUI/src/jper/service/models/harvester.py
import utils.connector.connector as DB
import utils.config as config
import json
from werkzeug.datastructures import MultiDict

class HarvesterModel():
    '''
    Provides a querys for getting data from ES 
    '''
    
    def __init__(self):
        self.__conn = DB.U_DBConnection().get_connection(config.DB_NAME)
        self.__match_all = {
            "query": {
                "match_all": {}
            }
        }
    
    def get_webservices(self):
        '''
        gets all webservices 
        
        Return:
            list of webbservices
        '''
        
        result = self.__conn.execute_search_query(config.WEBSERVICES_INDEX_NAME, config.WEBSERVICES_DOCTYPE_NAME, self.__match_all)
        return result['hits']['hits']
    
    def get_history(self):
        '''
        gets all webservices 
        
        Return:
            list of history
        '''
        return self.__conn.execute_search_query(config.HISTORY_INDEX_NAME, config.HISTORY_DOCTYPE_NAME, self.__match_all)
    
    def get_webservice(self, webservice_id):
        '''
        get webservice with all data
        
        Return:
            webservice object
        '''
        query = {
            "query": {
                "match": {
                    '_id' : str(webservice_id)
                              }
            }
        }
        
        print('query')
        
        result = self.__conn.execute_search_query(config.WEBSERVICES_INDEX_NAME, config.WEBSERVICES_DOCTYPE_NAME, query)
        return result['hits']['hits']
    
    def save_webservice(self, webservice):
        '''
        validate and save webservice object
        
        Return:
            webservice object
        '''
        pass
    
    def valid_webservice(self, webservice_id):
        ''' 
        valid all information from webservice and save it if everything goes ok
        
        '''
        pass
    
    def multidict_form_data(self,data):
        '''
        
        '''
        print(data)
        print(data[0]['_source'])
        return MultiDict(
                         [
                          ('url', data[0]['_source']['url']),
                          ('name',data[0]['_source']['name']),
                          ('query',data[0]['_source']['query']),
                          ('end_date',data[0]['_source']['end_date']),
                          ('frequency',data[0]['_source']['frequency']),
                          ('engine',data[0]['_source']['engine']),
                          ('active',data[0]['_source']['active']),
                          ('wait_window',data[0]['_source']['wait_window'])
                          ]
                         )

GUI/src/jper/service/forms/__init__.py
"""
This module contains all the model objects used by the system core.

All objects contained in sub-modules are also imported here, so that they can be imported elsewhere directly from this
module.

For example, instead of

::

    from service.models.notifications import UnroutedNotification
    from service.models.repository import RepositoryConfig

you can do

::

    from service.models import UnroutedNotification, RepositoryConfig

"""
# so that your models can all be accessed from service.models, you can import them here
from service.models.notifications import RoutedNotification, UnroutedNotification, RoutingMetadata, NotificationMetadata, FailedNotification
from service.models.repository import RepositoryConfig, MatchProvenance, RetrievalRecord
from service.models.api import NotificationList, IncomingNotification, OutgoingNotification, ProviderOutgoingNotification
from service.models.account import Account

GUI/src/jper/service/forms/webservice.py
'''
Created on 18 Nov 2015

Form for webservice

@author: Mateusz.Kasiuba
'''

from wtforms import Form, BooleanField, TextField, PasswordField, validators, SelectField
import utils.config as config
from utils.config import MULTI_PAGE, FREQUENCY_DAILY, FREQUENCY_WEEKLY,\
    FREQUENCY_MONTHLY

'''
name
url
query
email
end_date
frequency
engine
active
wait_window
'''
class WebserviceForm(Form):
    name = TextField('Name', [validators.Length(min=4, max=25), validators.Required()])
    url = TextField('Url', [validators.Length(min=6, max=35), validators.Required()])
    query = TextField('Query', [validators.Required()])
    email = TextField('Email', [validators.Email()])
    end_date = TextField('End Date', [validators.Required()])
    frequency =  SelectField('Frequency', choices=[(FREQUENCY_DAILY, 'Daily'), (FREQUENCY_WEEKLY, 'Weekly'), (FREQUENCY_MONTHLY, 'Monthly')])
    engine = SelectField('Engine', choices=[(MULTI_PAGE, 'MultiPage EPMC')])
    wait_window = TextField('Wait Window', [validators.Required(), validators.number_range(0)])
    active = BooleanField('Active')

GUI/src/jper/service/views/harvester.py
'''
Created on 18 Nov 2015

Webpage - Graphic User Interface for an harvester 

@author: Mateusz.Kasiuba
'''
import uuid, json, time, requests

from service.models.harvester import HarvesterModel
from service.forms.webservice import WebserviceForm

from flask import Blueprint, request, url_for, flash, redirect, make_response
from flask import render_template, abort
from flask.ext.login import login_user, logout_user, current_user

harvester = Blueprint('harvester', __name__)
harvesterModel = HarvesterModel()

#This is part of their code in my opinion we should move this part of code in common class
@harvester.before_request
def restrict():
    if current_user.is_anonymous():
        if not request.path.endswith('login'):
            return redirect(request.path.rsplit('/',1)[0] + '/login')
# end part of their code should be move in common class

@harvester.route('/webservice')
def webservice():
    '''
    Page with list of webservices installed in ES database
    '''
    if not current_user.is_super:
        abort(401)
    webservice = harvesterModel.get_webservices()
    return render_template('harvester/webservice.html', webservice_list = webservice)


@harvester.route('/history')
def history():
    '''
    Page with list history quesries form harvester
    '''
    if not current_user.is_super:
        abort(401)
    history = harvesterModel.get_history()
    return render_template('harvester/webservice.html', history_list = history)

@harvester.route('/details/<webservice_id>', methods=['GET','POST'])
def details(webservice_id):
    '''
    Page with details 
    '''
    if not current_user.is_super:
        abort(401)
    webservice = harvesterModel.get_webservice(webservice_id)
    return render_template('harvester/detail.html', webservice = webservice)


#To consider - better it will be use MANAGE instead ADD and EDIT but at this moment idk how
#I cannot create method and link to EDIT - idk why
@harvester.route('/edits/<webservice_id>', methods=['GET','POST'])
def edits(webservice_id):
    '''
    Page with details 
    '''
    if not current_user.is_super:
        abort(401)
        
    webservice = harvesterModel.get_webservice(webservice_id)
    form = WebserviceForm(harvesterModel.multidict_form_data(webservice))
        
    return render_template('harvester/edit.html', webservice = webservice, form = form)

@harvester.route('/add')
def add():
    '''
    Add new webservice
    '''
    return render_template('harvester/detail.html', webservice = webservice)

GUI/src/jper/service/templates/harvester/detail.html
{% extends "base.html" %}

{% block content %}

{{webservice}}
{% endblock %}

{% block extra_js_bottom %}
{% endblock extra_js_bottom %}

GUI/src/jper/service/templates/harvester/edit.html
{% extends "base.html" %}

{% block content %}

{% from "harvester/helpers/field_render.html" import render_field %}
<form method=post action="/register">
  <dl>
    {{ render_field(form.url) }}
    {{ render_field(form.name) }}
    {{ render_field(form.query) }}
    {{ render_field(form.email) }}
    {{ render_field(form.end_date) }}
    {{ render_field(form.frequency) }}
    {{ render_field(form.engine) }}
    {{ render_field(form.wait_window) }}
    {{ render_field(form.active) }}
  </dl>
  <button type="submit" class="btn btn-success">Save</button>
</form>



{% endblock %}

{% block extra_js_bottom %}
{% endblock extra_js_bottom %}

GUI/src/jper/service/templates/harvester/helpers/field_render.html
{% macro render_field(field) %}
  <dt>{{ field.label }}
  <dd>{{ field(**kwargs)|safe }}
  {% if field.errors %}
    <ul class=errors>
    {% for error in field.errors %}
      <li>{{ error }}</li>
    {% endfor %}
    </ul>
  {% endif %}
  </dd>
{% endmacro %}

GUI/src/jper/service/templates/harvester/history.html
{% extends "base.html" %}

{% block content %}

<table class="table table-hover">
<thead>
	<tr>
		<th>Id</th>
		<th>Name</th>
		<th>Engine&nbsp;Name</th>
		<th>Frequency</th>
		<th>Active</th>
		<th>Actions</th>
	</tr>
</thead>
{% set i = 0 %}
{% for webservice in history_list %}
{% set i = i +1 %}
{% set webservice = webservice['_source']%}
	<tr>
		<th scope='row'>{{i}}</th>
		<td>{{webservice['name']}}</td>
		<td>{{webservice['engine']}}</td>
		<td>{{webservice['frequency']}}</td>
		<td>{{webservice['active']}}</td>
		<td>
			<span class="glyphicon glyphicon-edit" aria-hidden="true"></span>
			<span class="glyphicon glyphicon glyphicon-remove" aria-hidden="true"></span>
		</td>
	</tr>
{% endfor %}
</table>



{% endblock %}

{% block extra_js_bottom %}
{% endblock extra_js_bottom %}

GUI/src/jper/service/templates/harvester/webservice.html
{% extends "base.html" %}

{% block content %}
<div class="row">
<div class='col-md-12'>
	<a href="{{ url_for('harvester.add') }}">
		<button type="button" class="btn btn-primary pull-right">Add webservice</button>
	</a>
<div>
</div>
	<table class="table table-hover">
	<thead>
		<tr>
			<th>Id</th>
			<th>Name</th>
			<th>Engine&nbsp;Name</th>
			<th>Frequency</th>
			<th>Active</th>
			<th>Actions</th>
		</tr>
	</thead>
	{% set i = 0 %}
	{% for webservice in webservice_list %}
	{% set i = i +1 %}
	{% set param = webservice['_source']%}
		<tr>
			<th scope='row'>{{i}}</th>
			<td>{{param['name']}}</td>
			<td>{{param['engine']}}</td>
			<td>{{param['frequency']}}</td>
			<td>{{param['active']}}</td>
			<td>
				<a href="{{ url_for('harvester.edits', webservice_id=webservice['_id']) }}">
					<span class="glyphicon glyphicon-edit" aria-hidden="true"></span>
				</a>
				<span class="glyphicon glyphicon glyphicon-remove" aria-hidden="true"></span>
			</td>
		</tr>
	{% endfor %}
	</table>
</div>
</div>
{% endblock %}

{% block extra_js_bottom %}
{% endblock extra_js_bottom %}